name: guifetch
description: A new Flutter project.

publish_to: 'none'

version: 0.0.3

environment:
  sdk: ">=3.0.5"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.0.1
  cupertino_icons: ^1.0.2
  image: ^4.0.17
  palette_generator: ^0.3.3+2
  flutter_improved_scrolling: ^0.0.3
  toml: ^0.13.1
  path: ^1.8.1
  drop_shadow_image: ^0.9.1
  flutter_acrylic: ^1.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/os_images/
